### ISSUE TITLE
Are you interested in freelancing?

### ISSUE THREAD

**Issue by ghost** [davamix/cats-localization#7]
@davamix Greetings,
currently I have a task that i want to be done, it's in detectron2.
I am willing to pay, Are you interested?

**Comment by davamix** [comment]
Hi @deepseek

Please, send me an email to davamix@gmail.com with more info about that task.

Thanks!

**Comment by ghost** [comment]
@davamix 
Have a look at the email that I sent you.
Set a delivery date and cost.
